@startuml 交互演示
actor 用户
entity 前端
entity 后端
database 数据库
用户 -> 前端: 设计表格，让前端去渲染
前端 -> 后端: 点击生成按钮，一次性传输所有相关数据给后端
后端 -> 数据库: 把这张表所有的相关信息持久化，留着后边使用
后端 -> 前端: 把生成的.xlsx提供给前端
前端 -> 用户: 提供.xlsx下载

用户 -> 前端: 查询历史记录
前端 -> 后端: 发送查询请求
后端 -> 数据库: 查询
数据库 -> 后端: 返回查询的数据
后端 -> 前端: 返回数据
前端 -> 用户: 提供给用户，提供增删改查

用户 -> 前端: 想要加载某个之前的表格
前端 -> 后端: 发送查询请求
后端 -> 数据库: 查询
数据库 -> 后端: 返回查询的数据
后端 -> 前端: 返回数据
前端 -> 用户: 在页面上渲染这些数据
@enduml